### ISSUE TITLE
Check cognate sets

### ISSUE THREAD

**Issue by chrzyki** [lexibank/davletshinaztecan#6]
I *think* there is something wrong with the cognate sets:

```
WARNING davletshinaztecan: Cross-concept cognate set 31
WARNING davletshinaztecan: Cross-concept cognate set 43
WARNING davletshinaztecan: Cross-concept cognate set 44
WARNING davletshinaztecan: Cross-concept cognate set 70
WARNING davletshinaztecan: Cross-concept cognate set 71
WARNING davletshinaztecan: Cross-concept cognate set 80
WARNING davletshinaztecan: Cross-concept cognate set 81
WARNING davletshinaztecan: Cross-concept cognate set 100
WARNING davletshinaztecan: Cross-concept cognate set 101
WARNING davletshinaztecan: Cross-concept cognate set 137
WARNING davletshinaztecan: Cross-concept cognate set 138
WARNING davletshinaztecan: Cross-concept cognate set 152
```

Judging from the [raw data](https://www.degruyter.com/document/doi/10.31826/jlr-2012-080106/html) this does not seem intended, e.g. cognates don't seem to be coded cross-concept wise.

**Comment by LinguList** [comment]
This should be accounted for, at least in the version I have here, and 
which I just updated, since the cogidx in the data is incremented, can 
you maybe check if there's something like 1 point missing? Such as 
`cogidx += max(cogids)+1`  (line 107)?

**Comment by chrzyki** [comment]
Yes, appears to be missing data and fixed with `+2` for the IDs. See https://github.com/lexibank/davletshinaztecan/commit/c0eb7fcbc78dad2bf9bb65dc76104b60f2dabe5f.

**Comment by LinguList** [comment]
I think this is not the problem, as I figured that some cognate sets are 
negative, so these will pull the cognate index down. Otherwise, teh 
counting logic was correct, but I did not count with the negative 
cognate IDs, which indicate borrowings and should be treated as singletons.

**Comment by chrzyki** [comment]
Alright, I'll leave this open then and revert to the old state for now.

**Comment by LinguList** [comment]
fixed now, if you check my changes. How did you find the problems?

**Comment by chrzyki** [comment]
Thanks, looks good. When I mass-build datasets I usually look for the `lexibank.check` cross-concept cognate warning. If there are warnings, I manually have a look at the data points and the forms/cognate tables.

**Comment by LinguList** [comment]
Thanks, I forgot/didnot know (?) about that command, need to add it to 
my shellscript!
